version: 2
jobs:
  build:
    working_directory: ~/online-training-deploy/
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout
      - run: bundle install
      - run: "cd online; ./build.sh"
      - run: cp -R cypher cypher-gadget images production ~/online-training-deploy
  publish:
    working_directory: ~/online-training-deploy/
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout
      - run: bundle install
#      - run: sudo apt-get update && sudo apt-get install -y awscli
#      - run: aws --region eu-west-1 s3 sync ~/circleci-publish/deploy/ s3://developer-pages.neo4j.com/wp/ --delete
#      - run:
#          name: "Publish"
#          command: "./render.rb all"
#          environment:
#            PUBLISH: true
#            BLOG_HOSTNAME: neo4j.com
#            BLOG_USERNAME: developer_site
#            ASCIIDOC_TEMPLATES_DIR: "_templates/wordpress"

workflows:
  version: 2
  developer-pages:
    jobs:
      - build:
#          filters:
#            branches:
#              only: gh-pages

      - publish:
#          filters:
#            branches:
#              only: publish
