version: 2
jobs:
  build-and-publish:
    working_directory: ~/online-training-build/
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout
      - run:
          name: "get deps"
          command:  bundle install
      - run:
          name: "install python3"
          command:  sudo apt-get install python python-pip
      - run:
          name: "install py modules"
          command: sudo pip install -r requirements.txt
      - run:
          name: "build and publish"
          command: "cd online; ./build_publish.sh"

workflows:
  version: 2
  developer-pages:
    jobs:
      - build-and-publish
